module.exports = {
  purge: ['./src/**/*.js', './src/**/*.jsx', './src/**/*.ts', './src/**/*.tsx'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    fontFamily: {
      sans: [
        'Open Sans',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      serif: [
        'Playfair Display',
        'ui-serif',
        'Georgia',
        'Cambria',
        'Times New Roman',
        'Times',
        'serif',
      ],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation Mono',
        'Courier New',
        'monospace',
      ],
    },
    screens: {
      sm: '100%',
      md: '640px',
      lg: '768px',
      xl: '1024px',
    },
    containers: { center: true, padding: '1rem' },
    extend: {
      colors: {
        'indigo-primary': '#5945e4',
      },
    },
  },
  variants: {
    extend: {
      display: ['hover', 'group-hover'],
      visibility: ['hover'],
      transform: ['active', 'group-hover'],
      translate: ['active', 'group-hover'],
      transitionProperty: ['hover', 'group-hover'],
      transitionDuration: ['hover', 'group-hover'],
      transitionTimingFunction: ['hover', 'group-hover'],
      transitionDelay: ['hover', 'group-hover'],
      animation: ['hover', 'group-hover'],
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
